### ISSUE TITLE
Build on macOS broken since commit 805a025a896994ed507c9704cce15221bac6a632

### ISSUE THREAD

**Issue by bstaletic** [google/cctz#96]
Commit https://github.com/google/cctz/commit/805a025a896994ed507c9704cce15221bac6a632 is in Abseil as of a few days ago and it has broken macOS CircleCI builds.

The linker error:
```
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      absl::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFStringGetCStringPtr", referenced from:
      absl::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFStringGetSystemEncoding", referenced from:
      absl::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFTimeZoneCopySystem", referenced from:
      absl::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFTimeZoneGetName", referenced from:
      absl::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
ld: symbol(s) not found for architecture x86_64
```

CircleCI run: https://circleci.com/gh/bstaletic/ycmd/241

**Comment by devjgm** [comment]
Thanks for the report. This issue is being discussed here: https://github.com/abseil/abseil-cpp/issues/283

**Comment by Mizux** [comment]
As quick fix you can use this commit https://github.com/abseil/abseil-cpp/pull/280/files
(you need to adapt it since it comes form abseil-cpp directory layout)

**Comment by bstaletic** [comment]
The author  PR that introduced the dependency on `CoreFoundation` said `CoreFoundation` is available as of Xcode 10. According to [wikipedia](https://en.wikipedia.org/wiki/Xcode) Xcode 10 came out in September 2018, which is about 6 months old.

There are a few problems I see with relying on Xcode specific tools:

- Downstream projects require compiler versions and are agnostic about IDEs. So if `CoreFoundation` is really an Xcode thing, that is not available for users who only install the toolchain (not the whole Xcode), those users won't be able to compile CCTZ.
  - I'm not a mac user, so I don't know if `CoreFoundation` is available without Xcode.
- Depending on something that has been available for about 6 months really doesn't go well with C++11 compatibility.

**Comment by devjgm** [comment]
I think there's some confusion somewhere. `CoreFoundation` is very old. It has been available always on Mac OS X (that's Mac OS 10). So, I think they meant mac os 10, not Xcode 10. See https://developer.apple.com/documentation/corefoundation saying macOS 10.0+

**Comment by bstaletic** [comment]
Okay, that's my bad. Thanks for correcting me.
